services:
  backend:
    container_name: backend
    build: .
    image: es-backend
    depends_on:
      - db-sample
    ports:
      - 8081:8081
    environment:
      - POSTGRES_DB=es-sample
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres-sample
      - POSTGRES_HOST=db-sample
      - AUTH_HOST=kc-dev # real domain name
      - AUTH_PORT=8080
      - AUTH_REALM=quickstart
      - KEYCLOAK_BACKEND_CLIENT_REALM=quickstart
      - KEYCLOAK_BACKEND_CLIENT_ID=admin-rest-backend
      - KEYCLOAK_BACKEND_CLIENT_SECRET=yWzrTIs2DWRX28mYhPPWgNrVewBYmU8a
      - SECURE_API=true
    networks:
      - es-backend-sample

  db-sample:
    container_name: db-sample
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=es-sample
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres-sample
    volumes:
      - es-pg-sample:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - es-backend-sample

  kc-dev:
    container_name: kc-dev
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-quickstart.json:/opt/keycloak/data/import/realm.json
    ports:
      - 8080:8080
    networks:
      - es-backend-sample

volumes:
  es-pg-sample:

networks:
  es-backend-sample: