server:
  port: 8080

spring:
  profiles.active: test
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5433/${POSTGRES_DB:es-test}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres-test}
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
server:
  port: 0

---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  liquibase.enabled: true

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
  jpa:
    hibernate.ddl-auto: none
  liquibase.enabled: true