server:
  port: 8080

spring:
  profiles.active: test
  datasource:
    url: jdbc:h2:mem:${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate.ddl-auto: create-drop

---
spring:
  config.activate.on-profile: test
server:
  port: 0

---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate.ddl-auto: create-drop

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate.ddl-auto: none