create sequence country_seq start with 1 increment by 50;
create sequence product_category_seq start with 1 increment by 50;
create sequence product_char_seq start with 1 increment by 50;
create sequence product_char_value_seq start with 1 increment by 50;
create sequence promo_seq start with 1 increment by 50;
create sequence shipping_method_seq start with 1 increment by 50;
create table address (is_default boolean, country_id bigint, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), customer_id varchar(255) not null, id varchar(255) not null, postal_code varchar(255), region varchar(255), street_num varchar(255), unit_num varchar(255), primary key (id));
create table country (id bigint not null, country_name varchar(255) unique, primary key (id));
create table customer (created_at timestamp(6) not null, deleted_at timestamp(6), modified_at timestamp(6), account_id varchar(255) unique, email varchar(255) unique, first_name varchar(255), id varchar(255) not null, last_name varchar(255), middle_name varchar(255), phone_num varchar(255), username varchar(255) unique, primary key (id));
create table customer_review (rating float(53), created_at timestamp(6) not null, deleted_at timestamp(6), modified_at timestamp(6), customer_id varchar(255), id varchar(255) not null, product_id varchar(255), text varchar(255), primary key (id));
create table order_item (price_per_item float(53), qty integer, total_amount float(53), id varchar(255) not null, product_id varchar(255), productsku varchar(255) not null, shop_order_id varchar(255), primary key (id));
create table payment (amount float(53), created_at timestamp(6) not null, id varchar(255) not null, payment_method varchar(255), shop_order_id varchar(255), primary key (id));
create table product (price float(53), qty_in_stock integer not null, created_at timestamp(6) not null, deleted_at timestamp(6), modified_at timestamp(6), product_category_id bigint, promo_id bigint, article varchar(255) not null unique, brand varchar(255), description varchar(255), id varchar(255) not null, name varchar(255) not null, product_icon varchar(255), sku varchar(255) not null unique, product_images varchar(255) array, primary key (id));
create table product_category (id bigint not null, parent_product_category_id bigint, description varchar(255), name varchar(255) not null, primary key (id), unique (name));
create table product_char_value_conf_m2m (product_char_value_id bigint not null, product_id varchar(255) not null, primary key (product_char_value_id, product_id));
create table product_char (id bigint not null, product_category_id bigint not null, name varchar(255) not null, primary key (id), unique (name, product_category_id));
create table product_char_value (id bigint not null, product_char_id bigint, value varchar(255) not null, primary key (id), unique (value, product_char_id));
create table promo (discount_rate float(53), created_at timestamp(6) not null, end_date timestamp(6), id bigint not null, modified_at timestamp(6), start_date timestamp(6), description varchar(255), name varchar(255), primary key (id));
create table shipping_method (created_at timestamp(6) not null, id bigint not null, modified_at timestamp(6), name varchar(255), price varchar(255), primary key (id));
create table shop_order (total_amount float(53), approved_at timestamp(6), created_at timestamp(6) not null, shipping_method_id bigint, customer_id varchar(255), id varchar(255) not null, shipping_address varchar(255), status varchar(255), primary key (id));
create table shopping_cart (total float(53) not null, created_at timestamp(6) not null, modified_at timestamp(6), customer_id varchar(255) unique, id varchar(255) not null, primary key (id));
create table shopping_cart_item (qty integer not null CHECK (qty > 0), created_at timestamp(6) not null, modified_at timestamp(6), id varchar(255) not null, product_id varchar(255) not null unique, shopping_cart_id varchar(255), primary key (id), unique (shopping_cart_id, product_id));