insert into category (created_at,description,modified_at,name,parent_id,id)
values (current_timestamp,'root category',current_timestamp,'Root Category',NULL,nextval('category_seq'));

insert into country (country_name, region, id)
values
('Afghanistan', 'South-Central Asia', nextval('country_seq')),
('Albania', 'Balkan Peninsula', nextval('country_seq')),
('Algeria', 'Northern Africa', nextval('country_seq')),
('American Samoa', 'Polynesia, Oceania', nextval('country_seq')),
('Andorra', 'Southern Europe', nextval('country_seq')),
('Angola', 'Central Africa', nextval('country_seq')),
('Anguilla', 'Leeward Islands, Caribbean', nextval('country_seq')),
('Antarctica', 'Antarctica', nextval('country_seq')),
('Antigua and Barbuda', 'Leeward Islands, Caribbean', nextval('country_seq')),
('Argentina', 'Southern South America', nextval('country_seq')),
('Armenia', 'Western Asia', nextval('country_seq')),
('Aruba', 'Leeward Islands, Caribbean', nextval('country_seq')),
('Australia', 'Australia/Oceania', nextval('country_seq')),
('Austria', 'Western Europe', nextval('country_seq')),
('Azerbaijan', 'Caucasus, Western Asia', nextval('country_seq')),
('Bahamas', 'Caribbean', nextval('country_seq')),
('Bahrain', 'Arabian Peninsula, Middle East', nextval('country_seq')),
('Bangladesh', 'South-Central Asia', nextval('country_seq')),
('Barbados', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Belarus', 'Eastern Europe', nextval('country_seq')),
('Belgium', 'Western Europe', nextval('country_seq')),
('Belize', 'Central America', nextval('country_seq')),
('Benin', 'West Africa', nextval('country_seq')),
('Bermuda', 'North America', nextval('country_seq')),
('Bhutan', 'South-Central Asia', nextval('country_seq')),
('Bolivia', 'Central South America', nextval('country_seq')),
('Bosnia and Herzegovina', 'Southern Europe', nextval('country_seq')),
('Botswana', 'Southern Africa', nextval('country_seq')),
('Brazil', 'Central Eastern South America', nextval('country_seq')),
('Brunei Darussalam', 'Southeast Asia', nextval('country_seq')),
('Bulgaria', 'Balkan, Eastern Europe', nextval('country_seq')),
('Burkina Faso', 'West Africa', nextval('country_seq')),
('Burundi', 'Eastern Africa, African Great Lakes', nextval('country_seq')),
('Cambodia', 'South-East Asia', nextval('country_seq')),
('Cameroon', 'Central Africa', nextval('country_seq')),
('Canada', 'North North America', nextval('country_seq')),
('Cape Verde', 'West Africa', nextval('country_seq')),
('Cayman Islands', 'Greater Antilles, Caribbean', nextval('country_seq')),
('Central African Republic', 'Central Africa', nextval('country_seq')),
('Chad', 'Central Africa', nextval('country_seq')),
('Chile', 'Western South America', nextval('country_seq')),
('China', 'Eastern Asia', nextval('country_seq')),
('Christmas Island', 'Southeast Asia', nextval('country_seq')),
('Cocos (Keeling) Islands', 'South-East Asia, Australia', nextval('country_seq')),
('Colombia', 'North West South America', nextval('country_seq')),
('Comoros', 'Eastern Africa', nextval('country_seq')),
('Democratic Republic of the Congo (Kinshasa)', 'Central Africa', nextval('country_seq')),
('Congo Republic of (Brazzaville)', 'Central Africa', nextval('country_seq')),
('Cook Islands', 'Polynesia, Oceania', nextval('country_seq')),
('Costa Rica', 'Central America', nextval('country_seq')),
('Côte D''ivoire (Ivory Coast)', 'West Africa', nextval('country_seq')),
('Croatia', 'Balkan Peninsula, Southern Europe', nextval('country_seq')),
('Cuba', 'Greater Antilles, Caribbean', nextval('country_seq')),
('Cyprus', 'Mediterranean, Western Asia', nextval('country_seq')),
('Czech Republic', 'Eastern Europe', nextval('country_seq')),
('Denmark', 'Northern Europe', nextval('country_seq')),
('Djibouti', 'Eastern Africa', nextval('country_seq')),
('Dominica', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Dominican Republic', 'Greater Antilles, Caribbean', nextval('country_seq')),
('East Timor (Timor-Leste)', 'South-East Asia', nextval('country_seq')),
('Ecuador', 'North West South America', nextval('country_seq')),
('Egypt', 'Africa, Middle East', nextval('country_seq')),
('El Salvador', 'Central America', nextval('country_seq')),
('Equatorial Guinea', 'Central Africa', nextval('country_seq')),
('Eritrea', 'Eastern Africa', nextval('country_seq')),
('Estonia', 'Northern Europe', nextval('country_seq')),
('Ethiopia', 'Eastern Africa', nextval('country_seq')),
('Falkland Islands', 'Southern South America', nextval('country_seq')),
('Faroe Islands', 'Northern Europe', nextval('country_seq')),
('Fiji', 'Melanesia, Oceania', nextval('country_seq')),
('Finland', 'Northern Europe', nextval('country_seq')),
('France', 'Western Europe', nextval('country_seq')),
('French Guiana', 'Northern South America', nextval('country_seq')),
('French Polynesia', 'Polynesia, Oceania', nextval('country_seq')),
('French Southern Territories', 'Southern Indian Ocean', nextval('country_seq')),
('Gabon', 'Central Africa', nextval('country_seq')),
('The Gambia', 'West Africa', nextval('country_seq')),
('Georgia', 'Caucasus', nextval('country_seq')),
('Germany', 'Western Europe', nextval('country_seq')),
('Ghana', 'West Africa', nextval('country_seq')),
('Gibraltar', 'Southern Europe', nextval('country_seq')),
('Greece', 'Southern Europe', nextval('country_seq')),
('Greenland', 'North America', nextval('country_seq')),
('Grenada', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Guadeloupe', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Guam', 'Micronesia, Oceania', nextval('country_seq')),
('Guatemala', 'Central America', nextval('country_seq')),
('Guinea', 'West Africa', nextval('country_seq')),
('Guinea Bissau', 'West Africa', nextval('country_seq')),
('Guyana', 'North Eastern South America', nextval('country_seq')),
('Haiti', 'Greater Antilles, Caribbean', nextval('country_seq')),
('Holy See', 'Southern Europe within Italy', nextval('country_seq')),
('Honduras', 'Central America', nextval('country_seq')),
('Hong Kong', 'Eastern Asia', nextval('country_seq')),
('Hungary', 'Eastern Europe', nextval('country_seq')),
('Iceland', 'Northern Europe', nextval('country_seq')),
('India', 'South-Central Asia', nextval('country_seq')),
('Indonesia', 'Maritime South-East Asia', nextval('country_seq')),
('Iran (Islamic Republic of)', 'South-Central Asia', nextval('country_seq')),
('Iraq', 'Middle East, Western Asia', nextval('country_seq')),
('Ireland', 'Northern Europe', nextval('country_seq')),
('Israel', 'Middle East, Western Asia', nextval('country_seq')),
('Italy', 'Southern Europe', nextval('country_seq')),
('Ivory Coast', 'West Africa', nextval('country_seq')),
('Jamaica', 'Greater Antilles, Caribbean', nextval('country_seq')),
('Japan', 'Eastern Asia', nextval('country_seq')),
('Jordan', 'Middle East, Western Asia', nextval('country_seq')),
('Kazakhstan', 'Central Asia', nextval('country_seq')),
('Kenya', 'Eastern Africa', nextval('country_seq')),
('Kiribati', 'Micronesia, Oceania', nextval('country_seq')),
('Korea Democratic People''s Rep. (North Korea)', 'Eastern Asia', nextval('country_seq')),
('Korea Republic of (South Korea)', 'Eastern Asia', nextval('country_seq')),
('Kosovo', 'Southern Europe', nextval('country_seq')),
('Kuwait', 'Middle East, Western Asia', nextval('country_seq')),
('Kyrgyzstan', 'Central Asia', nextval('country_seq')),
('Lao People''s Democratic Republic', 'South-East Asia', nextval('country_seq')),
('Latvia', 'Northern Europe', nextval('country_seq')),
('Lebanon', 'Middle East, Western Asia', nextval('country_seq')),
('Lesotho', 'Southern Africa', nextval('country_seq')),
('Liberia', 'West Africa', nextval('country_seq')),
('Libya', 'Northern Africa', nextval('country_seq')),
('Liechtenstein', 'Western Europe', nextval('country_seq')),
('Lithuania', 'Northern Europe', nextval('country_seq')),
('Luxembourg', 'Western Europe', nextval('country_seq')),
('Macau', 'Eastern Asia', nextval('country_seq')),
('Madagascar', 'Eastern Africa', nextval('country_seq')),
('Malawi', 'Eastern Africa', nextval('country_seq')),
('Malaysia', 'Southeast Asia', nextval('country_seq')),
('Maldives', 'South-Central Asia', nextval('country_seq')),
('Mali', 'West Africa', nextval('country_seq')),
('Malta', 'Southern Europe', nextval('country_seq')),
('Marshall Islands', 'Micronesia, Oceania', nextval('country_seq')),
('Martinique', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Mauritania', 'West Africa', nextval('country_seq')),
('Mauritius', 'Eastern Africa', nextval('country_seq')),
('Mayotte', 'Eastern Africa', nextval('country_seq')),
('Mexico', 'North America', nextval('country_seq')),
('Micronesia Federal States of', 'Micronesia, Oceania', nextval('country_seq')),
('Moldova Republic of', 'Eastern Europe', nextval('country_seq')),
('Monaco', 'Southern Europe', nextval('country_seq')),
('Mongolia', 'Eastern Asia', nextval('country_seq')),
('Montenegro', 'Southern Europe', nextval('country_seq')),
('Montserrat', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Morocco', 'Northern Africa', nextval('country_seq')),
('Mozambique', 'Eastern Africa', nextval('country_seq')),
('Myanmar Burma', 'Southeast Asia', nextval('country_seq')),
('Namibia', 'Southern Africa', nextval('country_seq')),
('Nauru', 'Micronesia, Oceania', nextval('country_seq')),
('Nepal', 'South-Central Asia', nextval('country_seq')),
('Netherlands', 'Western Europe', nextval('country_seq')),
('Netherlands Antilles', 'Caribbean', nextval('country_seq')),
('New Caledonia', 'Melanesia, Oceania', nextval('country_seq')),
('New Zealand', 'Oceania; Australia', nextval('country_seq')),
('Nicaragua', 'Central America', nextval('country_seq')),
('Niger', 'West Africa', nextval('country_seq')),
('Nigeria', 'West Africa', nextval('country_seq')),
('Niue', 'Polynesia, Oceania', nextval('country_seq')),
('North Macedonia', 'Balkan Peninsula, Southern Europe', nextval('country_seq')),
('Northern Mariana Islands', 'Micronesia, Oceania', nextval('country_seq')),
('Norway', 'Northern Europe', nextval('country_seq')),
('Oman', 'Middle East', nextval('country_seq')),
('Pakistan', 'South-Central Asia', nextval('country_seq')),
('Palau', 'Micronesia, Oceania', nextval('country_seq')),
('Palestinian territories', 'Middle East, Western Asia', nextval('country_seq')),
('Panama', 'Central America', nextval('country_seq')),
('Papua New Guinea', 'Maritime Southeast Asia, Melanesia, Oceania', nextval('country_seq')),
('Paraguay', 'Central South America', nextval('country_seq')),
('Peru', 'Western South America', nextval('country_seq')),
('Philippines', 'Southeast Asia', nextval('country_seq')),
('Pitcairn Island', 'Polynesia, Oceania', nextval('country_seq')),
('Poland', 'Eastern Europe', nextval('country_seq')),
('Portugal', 'Southern Europe', nextval('country_seq')),
('Puerto Rico', 'Greater Antilles, Caribbean', nextval('country_seq')),
('Qatar', 'Arabian Peninsula, Middle East', nextval('country_seq')),
('Reunion Island', 'Eastern Africa', nextval('country_seq')),
('Romania', 'Eastern Europe', nextval('country_seq')),
('Russian Federation', 'Eastern Europe - Northern Asia', nextval('country_seq')),
('Rwanda', 'Eastern Africa, African Great Lakes', nextval('country_seq')),
('Saint Kitts and Nevis', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Saint Lucia', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Saint Vincent and the Grenadines', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Samoa', 'Polynesia, Oceania', nextval('country_seq')),
('San Marino', 'Southern Europe within Italy', nextval('country_seq')),
('Sao Tome and Principe', 'Central Africa', nextval('country_seq')),
('Saudi Arabia', 'Arabian Peninsula, Middle East', nextval('country_seq')),
('Senegal', 'West Africa', nextval('country_seq')),
('Serbia', 'Southern Europe', nextval('country_seq')),
('Seychelles', 'Eastern Africa', nextval('country_seq')),
('Sierra Leone', 'West Africa', nextval('country_seq')),
('Singapore', 'Southeast Asia', nextval('country_seq')),
('Slovakia (Slovak Republic)', 'Eastern Europe', nextval('country_seq')),
('Slovenia', 'Southern Europe', nextval('country_seq')),
('Solomon Islands', 'Melanesia, Oceania', nextval('country_seq')),
('Somalia', 'Eastern Africa', nextval('country_seq')),
('South Africa', 'Southern Africa', nextval('country_seq')),
('South Sudan', 'East-Central Africa', nextval('country_seq')),
('Spain', 'Southern Europe', nextval('country_seq')),
('Sri Lanka', 'South-Central Asia', nextval('country_seq')),
('Sudan', 'Northern Africa', nextval('country_seq')),
('Suriname', 'North-Eastern South America', nextval('country_seq')),
('Swaziland (Eswatini)', 'Southern Africa', nextval('country_seq')),
('Sweden', 'Northern Europe', nextval('country_seq')),
('Switzerland', 'Western Europe', nextval('country_seq')),
('Syria Syrian Arab Republic', 'Middle East, Western Asia', nextval('country_seq')),
('Taiwan (Republic of China)', 'Eastern Asia', nextval('country_seq')),
('Tajikistan', 'Central Asia', nextval('country_seq')),
('Tanzania officially the United Republic of Tanzania', 'Eastern Africa', nextval('country_seq')),
('Thailand', 'South-East Asia', nextval('country_seq')),
('Tibet', 'South-Central Asia', nextval('country_seq')),
('Timor Leste (East Timor)', 'Maritime South-East Asia', nextval('country_seq')),
('Togo', 'West Africa', nextval('country_seq')),
('Tokelau', 'Oceania/Australia', nextval('country_seq')),
('Tonga', 'Polynesia, Oceania', nextval('country_seq')),
('Trinidad and Tobago', 'Northern South America, Caribbean', nextval('country_seq')),
('Tunisia', 'Northern Africa', nextval('country_seq')),
('Turkey', 'Southeastern Europe, Western Asia', nextval('country_seq')),
('Turkmenistan', 'Central Asia', nextval('country_seq')),
('Turks and Caicos Islands', 'Caribbean, parts of the Bahamas island chain.', nextval('country_seq')),
('Tuvalu', 'Polynesia, Oceania', nextval('country_seq')),
('Uganda', 'Eastern Africa', nextval('country_seq')),
('Ukraine', 'Eastern Europe', nextval('country_seq')),
('United Arab Emirates', 'Arabian Peninsula, Middle East', nextval('country_seq')),
('United Kingdom', 'Northern Europe', nextval('country_seq')),
('United States', 'North America', nextval('country_seq')),
('Uruguay', 'Central East South America', nextval('country_seq')),
('Uzbekistan', 'Central Asia', nextval('country_seq')),
('Vanuatu', 'Melanesia, Oceania', nextval('country_seq')),
('Vatican City State (Holy See)', 'Southern Europe within Italy', nextval('country_seq')),
('Venezuela', 'Northern South America', nextval('country_seq')),
('Vietnam', 'South-East Asia', nextval('country_seq')),
('Virgin Islands (British)', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Virgin Islands (U.S.)', 'Lesser Antilles, Caribbean', nextval('country_seq')),
('Wallis and Futuna Islands', 'Polynesia, Oceania', nextval('country_seq')),
('Western Sahara', 'Northern Africa', nextval('country_seq')),
('Yemen', 'Arabian Peninsula, Middle East', nextval('country_seq')),
('Zambia', 'Eastern Africa', nextval('country_seq')),
('Zimbabwe', 'Eastern Africa', nextval('country_seq'));